rtabmap:
  ros__parameters:
    approx_sync: true
    qos_image: 2
    qos_camera_info: 2
    
    wait_for_transform: 2.0

    subscribe_depth: true 
    subscribe_rgb: true
    subscribe_odom: true
    
    frame_id: "base_link"
    odom_frame_id: "odom"
    map_frame_id: "map"
    publish_tf: true

    topic_queue_size: 50
    sync_queue_size: 50

    Rtabmap/DetectionRate: "10"      
    RGBD/LinearUpdate: "0.1"         
    RGBD/AngularUpdate: "0.1"   

    Reg/Force3DoF: "true"     
    
    Kp/DetectorStrategy: "2"         
    Vis/FeatureType: "2"             
    Reg/Strategy: "0"                
    
    # 3D-2D estimation (1) or 3D-3D (0). 
    # '2' was for pure 2D epipolar (monocular).
    Vis/EstimationType: "1"          
    Vis/MinInliers: "15"             
    Vis/MaxFeatures: "1000"          

    RGBD/CreateOccupancyGrid: "true"

rtabmap_viz:
  ros__parameters:
    approx_sync: true
    qos_image: 2
    qos_camera_info: 2

    wait_for_transform: 2.0
    
    subscribe_depth: true
    subscribe_rgb: true
    subscribe_odom: true
    
    frame_id: "base_link"
    odom_frame_id: "odom"

rgbd_odometry:
  ros__parameters:
    approx_sync: true
    qos_image: 2
    qos_camera_info: 2
    wait_for_transform: 2.0
    # Enable IMU for true Visual-Inertial Odometry inside RTAB-Map
    wait_imu_to_init: true 

    Odom/Force2D: "true"
    
    # Copy your tuning parameters here so the odometry node actually uses them
    Odom/Strategy: "0" # Frame-to-Map (F2M)
    Vis/EstimationType: "1"          
    Vis/MinInliers: "15"             
    Vis/MaxFeatures: "1000"