#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
import cv2
import torch
from transformers import pipeline
from PIL import Image as PILImage
import numpy as np

class AIDepthPreview(Node):
    def __init__(self):
        super().__init__('ai_depth_preview')
        self.bridge = CvBridge()
        
        # Subscribe to the decompressed topic generated by image_transport
        self.subscription = self.create_subscription(
            Image,
            '/camera/image_raw_decompressed', 
            self.image_callback,
            10)
            
        self.get_logger().info("Loading AI Depth Model onto GPU (this may take a moment to download on first run)...")
        
        # Auto-detect CUDA on your Lenovo LOQ
        device = 0 if torch.cuda.is_available() else -1
        
        # Initialize Depth Anything V2 (Small model is perfect for real-time edge processing)
        self.depth_estimator = pipeline(
            task="depth-estimation", 
            model="depth-anything/Depth-Anything-V2-Small-hf", 
            device=device
        )
        self.get_logger().info("Model loaded successfully! Waiting for the rover's camera stream...")

    def image_callback(self, msg):
        try:
            # 1. Convert ROS Image to OpenCV format
            # Using 'passthrough' or 'bgr8' depending on the exact stream format
            cv_image = self.bridge.imgmsg_to_cv2(msg, desired_encoding='bgr8')
            
            # 2. Convert to PIL Image for the Transformers pipeline
            pil_img = PILImage.fromarray(cv2.cvtColor(cv_image, cv2.COLOR_BGR2RGB))
            
            # 3. Run Inference on the GPU
            result = self.depth_estimator(pil_img)
            depth_pil = result["depth"]
            
            # 4. Convert depth map back to OpenCV array
            depth_cv = np.array(depth_pil)
            
            # 5. Normalize and apply a colormap (INFERNO provides excellent depth contrast)
            depth_normalized = cv2.normalize(depth_cv, None, 0, 255, cv2.NORM_MINMAX, dtype=cv2.CV_8U)
            depth_colormap = cv2.applyColorMap(depth_normalized, cv2.COLORMAP_INFERNO)
            
            # 6. Display both feeds side-by-side
            cv2.imshow("Raw Rover Stream", cv_image)
            cv2.imshow("AI Depth Map", depth_colormap)
            cv2.waitKey(1)
            
        except Exception as e:
            self.get_logger().error(f"Error processing frame: {e}")

def main(args=None):
    rclpy.init(args=args)
    node = AIDepthPreview()
    
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()
        cv2.destroyAllWindows()

if __name__ == '__main__':
    main()